### ISSUE TITLE
Error reported in function sctest in efp.py

### ISSUE THREAD

**Issue by myzhenghr** [mortvest/bfast-py#3]
Hi, Dmitry Serykh,

Thank you for your excellent work.
I try to run your code with my own data, and got an error with the code >`if (nd:=np.ndim(x))==1` in function sctest in line 102 in efp.py.
I am new in coding and BFAST, and have no idea how to solve it. 
Could you please fix this problem? Thank your so much.

Regards,
Henry

**Comment by mortvest** [comment]
Hi Henry,

What kind of error are you getting? What version of Python are you using? 
If had to guess, the version of Python that you are using is too old. It needs too be >= 3.8 in order to work.

Best wishes,
Dmitry

**Comment by myzhenghr** [comment]
Hi, Dmitry Serykh,
Thank you for your reply. The version of Python I used is 3.7.8 and looks like I missed some new properties in Python. 
I will update it immediately.

Thanks again.
Henry
