### ISSUE TITLE
Bfast for sentinel-2 chlorophyll-a

### ISSUE THREAD

**Issue by dmenneck** [mortvest/bfast-py#4]
Hey Dmitry,

great work on your bfast implementation! 

I'd like to use the bfast algorithm for sentinel-2 derived chloropyll-a data. Is it possible to use your version of 
the bfast algorithm for that kind of time series data?

Cheers,
Dirk

**Comment by mortvest** [comment]
Hi Dirk,

Thanks! 

I have a very limited knowledge of remote sensing, so I sadly can't help you with this question. This implementation is meant to be equivalent to the R version (with fewer supported parameters and return values). So if the R version can be used for your application, my version should also work. This implementation was meant to be an early prototype, so there could be differences between the versions. 
I am also working on a highly efficient GPU-based [implementation](https://github.com/diku-dk/bfast/tree/bfast-experimental) of the BFAST algorithm, that can also be of use for you (still in early development). 

Best wishes,
Dmitry
